dist: bionic
language: node_js
node_js: '13'

services:
  - docker
  - redis-server

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install --no-audit --loglevel=error --no-fund --no-optional --no-package-lock --no-progress --no-save --no-shrinkwrap
  - npm run phoenix:ci

script:
  - npm update
  - npm run lint
  - npm run test:ci

jobs:
  include:
    - stage: Release packages
      if: branch = master AND NOT type = pull_request
      script:
        - sh .travis-release.sh
