dist: bionic
language: node_js
node_js: '13'

addons:
  chrome: stable

services:
  - docker
  - redis-server
  - xvfb

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"

install:
  - GITHUB_USER=sui-bot GITHUB_EMAIL=cloud-accounts@scmspain.com npm run phoenix:ci

script:
  - npm run lint
  - npm run test:ci
  - npm run test:e2e

jobs:
  include:
    - stage: Release packages
      if: branch = master AND NOT type = pull_request
      script:
        - npx @s-ui/ci release
